sudo: required
service:
    - docker

before_install:
    - docker build -t davechri/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true davechri/react-test npm test

after_success:
    - docker build -t davechri/multi-client ./client
    - docker build -t davechri/multi-nginx ./nginx
    - docker -t davechri/multi-server ./server
    - docker -t davechri/multi-worker ./worker
    # Log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push davechri/multi-client
    - docker push davechri/multi-nginx
    - docker push davechri/multi-server
    - docker push davechri/multi-worker